#!/usr/bin/Rscript

# import csv
csco <- read.csv(file="csco.csv",head=FALSE,sep=",")
#csco

# select rows for March 2000
march2000 = csco[c(545:567),]
#march2000

# select hlc (high, low, close)
hlc = march2000[, c("V4","V5","V6")]
#hlc

# select c (close)
c = hlc[, c("V6")]
#c 

# plot array and save to png
#png('plot.png')
svg('plot.svg')
plot(c, xlab = "", ylab = "",
     type = "o", # connect dots
     col = "red",
     xlim = c(1,31),
     ylim = c(60,80))

title(main = list("Cisco Stock Price (March 2000)",
                  cex = 1.5,
                  col = "red",
                  font = 3))
title(xlab = "Day")
title(ylab = "Closing Price ($)")



dev.off()

# display plot in brower
browseURL("plot.svg")
