#!/usr/bin/Rscript

# import csv
csco <- read.csv(file="csco.csv",head=FALSE,sep=",")
colnames(csco) <- c("d","V2","o","h","l","c","v") # date, V2, open, high, low, close, volume)
#csco

# select rows for March 2000
march2000 = csco[c(545:567),]
#march2000

# select hlc (date, high, low, close)
dhlc = march2000[, c("d","h","l","c")]
#hlc

# select dc (date, close)
#dc = dhlc[, c("d","c")]
#dc 

# select d (date)
d = dhlc[, c("d")]
#d 
# convert data to day
subtrahend = 20000300
d = d - subtrahend
#d

# select c (close)
c = dhlc[, c("c")]
#c 

# combine columns
dc = cbind(d, c)
#dc

# plot array and save to png
png('plot.png')
svg('plot.svg')
plot(dc, xlab = "", ylab = "",
    type = "o", # connect dots
    col = "red",
    xlim = c(1,31),
    ylim = c(60,80))

title(main = list("Cisco Stock Price (March 2000)",
                 cex = 1.5,
                 col = "red",
                 font = 3))
title(xlab = "Day")
title(ylab = "Closing Price ($)")

dev.off()

# display plot in brower
browseURL("plot.svg")
